[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit DHT sensor library@^1.4.4
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit BME680 Library@^2.0.3
    adafruit/Adafruit MPU6050@^2.0.6
    adafruit/Adafruit HMC5883 Unified@^1.2.1
    adafruit/Adafruit BH1750@^1.0.2
    adafruit/Adafruit SSD1306@^2.5.7
    arduino-libraries/ArduinoOTA@^1.0
    links2004/WebSockets@^2.4.0
    milesburton/DallasTemperature@^3.9.0
    paulstoffregen/OneWire@^2.3.7
    bblanchon/ArduinoJson@^6.21.2
    miguelbalboa/MFRC522@^1.4.10
    kotyara12/GyverOS@^1.11
    https://github.com/espressif/esp-idf.git

build_flags =
    -D ARDUINO_LOOP_STACK_SIZE=8192
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -std=gnu++17
